Repository Islandora-Devops/isle-dc, pull requests merged in 2020-04, with the labels that each got.

#51 PRE-MERGE Work: Built and pushed new isle-alpaca image to Islandora D…
  docker-compose.yml
Labels: PRE-MERGE MVP2&3

#52 PRE-MERGE WORK: Updated isle-fcrepo image Dockerhub location from bor…
  docker-compose.yml
Labels: ISLE8-Sprint4, PRE-MERGE MVP2&3

#53 PRE-MERGE WORK: Official Lyrasis Blazegraph 2.1.5 image has curl. Tha…
  docker-compose.yml
Labels: PRE-MERGE MVP2&3

#54 PRE-MERGE-WORK: isle-houdini Dockerhub location changed to islandora,…
  docker-compose.yml
Labels: PRE-MERGE MVP2&3

#55 PRE-MERGE WORK: Updated isle-homarus Dockerhub location from borndigi…
  docker-compose.yml
Labels: PRE-MERGE MVP2&3

#57 PRE-MERGE WORK: Updated isle-hypercube Dockerhub location from borndi…
  docker-compose.yml
Labels: PRE-MERGE MVP2&3

#58 PRE-MERGE WORK: Updated isle-crayfits Dockerhub location from borndig…
  docker-compose.yml
Labels: PRE-MERGE MVP2&3

#16 All wired up
  .env
  docker-compose.yml
  scripts/islandora/install-islandora.sh
Labels: PRE-MERGE MVP2&3

#63 PRE-MERGE WORK: Removing alias artifact in traefik from previous merge
  docker-compose.yml
Labels: PRE-MERGE MVP2&3, traefik

#65 Post-merge fix. Issue #29 - Replaced drupal_db service name with form…
  docker-compose.yml
Labels: drupal, mariadb
